/** Declaration file generated by dts-gen */

export function addWords(wordList: any): any;

export function isMessageDirty(message: string): boolean;

export function maskBadWords(message: any, maskWith: any): any;

export function removeWords(wordList: any): any;
