/** Declaration file generated by dts-gen */

export function addWords(wordList: string[]): any;

export function isMessageDirty(message: string): boolean;

export function maskBadWords(message: string, maskWith: any): any;

export function removeWords(wordList: string[]): any;
