name: Push-to-EC2

on: push

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v4.1.10
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: "ec2-user@ec2-3-109-59-154.ap-south-1.compute.amazonaws.com"
          REMOTE_USER: "ec2-user"
          TARGET: "/home/ec2-user/cafe_map"
          SCRIPT_AFTER: |
            cd /home/ec2-user/cafe_map
            cd client_cafemap && pnpm run build && pnpm run send-client && cd ..
            cd server && pnpm run build && cd ..
            pm2 reload all
            echo $RSYNC_STDOUT